language: rust
cache:
  - cargo
  - pip

jobs:
  include:
    - script:
      - cargo build --verbose
    - before_script:
      - python3 -m pip install --upgrade pip --user
      - pip3 install -r requirements.txt
      - ls *.py|xargs -n 1 python3
      script:
        - cargo test
